### ISSUE TITLE
Update to OpenTherm Gateway 5.2

### ISSUE THREAD

**Issue by PvdGulik** [ebaauw/homebridge-otgw#12]
Since a few weeks the OTGW had updated to 5.2, more info: http://otgw.tclcode.com/changelog.html

Now I updated to version 5.2 in the log of Homebridge I see the following message:

"warming: recommanded version : OpenTherm Gateway v5.1"

Do you have plans to update your plug-in to support version 5.2?

Thanks

**Comment by ebaauw** [comment]
Hadn't yet seen that a new version is available, thanks.  From the change log, I don't expect any issues.  It seems to add support for some OpenTherm 3 features, that my new Boiler and Thermostat provide, so I definitely want to upgrade.

**Comment by ebaauw** [comment]
In v2.0.2.
