### ISSUE TITLE
Every night a Warning!

### ISSUE THREAD

**Issue by PvdGulik** [ebaauw/homebridge-otgw#13]
Hello, thanks for your nice Homebridge-OTGW plug-in. It's working perfect. But, every nigth I around 0:15, I get a message that there is a leakage in the boiler. But the boiler does not give any errors. So I think it's another signal which might be translated wrong. Is that possible? 
At 0:15 I send a task in HomeKit to switch of all lights, but there is no accessoire related to the boiler or thermostat included. So I don't think is related.

Thanks for your respond.

**Comment by ebaauw** [comment]
_Leak Detected_ is set when bit 0 in the low (slave) byte in the _Status_ telegram (message id: 00) has been set.  Same as _Status Fault_.  The OpenTherm Monitor shows this a _Fault indicaton_ at the bottom of the left column of check boxes.

Best check the log in the OpenTherm Monitor to see if your boiler (the OpenTherm slave) actually sets this bit.  Alternatively, set _Log Level_ to 2 in HomeKit and enable Homebridge debug mode, for Homebridge OTGW to log the telegrams.

**Comment by PvdGulik** [comment]
Thanks for your quick response. How do I set Log Level 2 in HomeKit. There's as far as I know no Logging in HomeKit, and no setting for Log Levels. Thanks.

I already enabled debuut mode in Homebridge. But last night no Leak Detected alarm occured. Related?

Thanks

**Comment by PvdGulik** [comment]
Goodmorning, after enabeling debug mode in Homebridge for two days, the error did not occurred. After disableing debug mode last night, it came back. Coincidence or?

By the way,I cannot use OT-monitor because I don't have Windows, only macOS and raspberry...

Thanks..

**Comment by ebaauw** [comment]
Turning on or off debug mode shouldn’t impact the functionality.

I’ve been running OT Monitor on a Raspberry Pi since I got the OT gateway.  There are Pi-specific versions on http://otgw.tclcode.com/download.html#utilities.
