### ISSUE TITLE
open therm gateway

### ISSUE THREAD

**Issue by antonlamers** [ebaauw/homebridge-otgw#15]
Hi,

Can you add support with this otgw software:
https://github.com/rvdbreemen/OTGW-firmware

thanks
Anton

**Comment by ebaauw** [comment]
No.  It looks like it provides a completely different interface, so that would require a completely different Homebridge plugin.  I've been running the standard OTGW firmware, which serves me well.  I'm not looking to change anything to my setup.

**Comment by antonlamers** [comment]
Hoi 
Dat weet ik niet of het anders is, want het werkt met de print van nodoshop en ook de firmware op het IC van http://otgw.tclcode.com/.

**Comment by ebaauw** [comment]
If it would provide the same interface, I wouldn't have to change anything in Homebridge OTGW, now would I?
