### ISSUE TITLE
Latest version not working

### ISSUE THREAD

**Issue by ghost** [ebaauw/homebridge-otgw#4]
Hi, 

Hope it is okay to seek help this way.
I've been using the Homebridge-otgw with Hoobs and it has been working very well. This morning I noticed that there was a new version, I updated, and now it just doesn't want to work anymore. 
I removed and installed again, rebooted the gateway, rebooted the pi. Updated the firmware on the gateway.

The result seems to always be that I get these log entries:
[OTGW] Initializing OTGW platform...
[OTGW] homebridge-otgw v1.1.2, node 12.16.3, homebridge v1.1.6, homebridge-lib v5.0.0
[OTGW] restored 4 accessories from cache
[OTGW] warning: heartbeat 0, drift 2011
[OTGW] warning: heartbeat 1, drift 1064
[OTGW] connected to OpenTherm Monitor at ws://192.168.1.45:8081/message.ws
[OTGW] warning: T10010600: out of sequence OpenTherm message - reset sequence

And that is where it stops, all the normal status messages that I am used to seeing are gone. It just stops there.

Looking at the webinterface of the gateway itself all seems normal, I can see the messages come past.

Hope the description is clear enough, if I can somehow provide more information to help you help me please let me know.

**Comment by ebaauw** [comment]
Do you see messages appearing constantly in the _Log_ tab of the OpenTherm Monitor?  I took me some effort to get things running again, after updating the firmware of the OpenTherm Gateway.  I think I ended up power cycling the Gateway, restarting the Monitor, and then restarting Homebridge.

I don’t use HOOBS, and I don’t understand what they’re doing.  I strongly recommend to use a standard Homebridge installation.  In general, my plugins don’t run under HOOBS; they make some changes to them while “certifying” them.  Please contact them for support.

**Comment by mkellsy** [comment]
HOOBS uses Homebridge 1.1.6 and doesn't modify plugins at all. I think he needs to upgrade Node to version 14.

**Comment by ghost** [comment]
Wasn't smooth, but I managed to update Node and that did in fact fix the problem.

**Comment by ghost** [comment]
I will cose it now as it's fixed. Thanks.
