### ISSUE TITLE
intergas thermostaat

### ISSUE THREAD

**Issue by trik430** [ebaauw/homebridge-otgw#5]
Hi Erik,

Can I add Intergas to homebridge? I installed homebridge on rpi and add plugin otgw.
Do you have a video or guideline how to do?
Thank you
Trik

**Comment by ebaauw** [comment]
If the OTGW supports the Intergas, it should work with Homebridge OTGW.  There are some Intergas boilers and one thermostat mentioned on the OTGW device list: http://otgw.tclcode.com/matrix.cgi.

See the README for how to setup Homebridge OTGW.

**Comment by trik430** [comment]
Hi Erik,

Thanks for your reply. I can see that my boiler is supported and also the thermostat (hre 36/30 kombi +intergas thermostat).
Whats should I fill in the plugin details? Sorry for asking simple questions but I'm not so handy.

I have a login if I want to connect my boiler. Should I enter this somewhere?


![Schermafbeelding 2020-12-26 om 17 36 06](https://user-images.githubusercontent.com/76602618/103155576-71d4a480-47a1-11eb-8add-231fdf172964.png)
![Schermafbeelding 2020-12-26 om 17 39 33](https://user-images.githubusercontent.com/76602618/103155577-74cf9500-47a1-11eb-81c9-3830e1f9802f.png)

Thanks again

**Comment by trik430** [comment]
Hi Erik,

Thanks for your reply. I can see that my boiler is supported and also the thermostat (hre 36/30 kombi +intergas thermostat).
Whats should I fill in the plugin details? Sorry for asking simple questions but I'm not so handy.

I have a login if I want to connect my boiler. Should I enter this somewhere?

Thanks again

![Schermafbeelding 2020-12-26 om 17 43 02](https://user-images.githubusercontent.com/76602618/103155654-063f0700-47a2-11eb-8927-97f2dee3df11.png)
![Schermafbeelding 2020-12-26 om 17 36 06](https://user-images.githubusercontent.com/76602618/103155655-08a16100-47a2-11eb-8b6e-31f4c87b1d29.png)

**Comment by ebaauw** [comment]
> I have a login if I want to connect my boiler.

Homebridge OTGW connects to the OpenTherm Gateway, see the prerequisites, not to your boiler's Internet gateway.

**Comment by trik430** [comment]
thank you. So means I need to add one more hardware. I thought with the homebridge and the gateway from incomfort it should work.
Pitty as I already can use the intergas app to change on distance only missing honest function.

**Comment by trik430** [comment]
one more info.
I can change the temp via the gateway so thought this is sufficient.
![Schermafbeelding 2020-12-27 om 23 20 34](https://user-images.githubusercontent.com/76602618/103180882-76c94f00-489a-11eb-82df-b69379400bf2.png)

**Comment by ebaauw** [comment]
Google seems to suggest the incomfort gateway does provide a (cloud based) REST API, so, at least in theory, a Homebridge plugin could be created for it.  It's very different from the (non-REST) API that the OpenTherm gateway provides, so Homebridge OTGW is of no help here.

**Comment by thephantom** [comment]
> one more info. I can change the temp via the gateway so thought this is sufficient. ![Schermafbeelding 2020-12-27 om 23 20 34](https://user-images.githubusercontent.com/76602618/103180882-76c94f00-489a-11eb-82df-b69379400bf2.png)

did you ever find an solution trik430?

**Comment by rvt** [comment]
If you end up from google here because you want to have intergas gateway enabled with homebridge, you can use this : https://github.com/staromeste/homebridge-http-advanced-accessory/issues/53
