### ISSUE TITLE
Witch ip adres in host

### ISSUE THREAD

**Issue by antonlamers** [ebaauw/homebridge-otgw#6]
hi, i have been running the otgw for years with complete satisfaction in domoticz. am now playing with homebridge. What do I need to fill in for host? I run homebride on the same radpberry that also runs domoticz. if I enter the same ip address as domoticz at host, then I do not see the remeha isense change when I change the temp in the home app. I don't enter anything at host either.

**Comment by ebaauw** [comment]
See the README: You need to specify the IP address and port of the OpenTherm Monitor under `host`.  If you don't run the Monitor, you might specify the IP address and port of the NodeMCU module in the OpenTherm Gateway under `otgw`.  I do find it only supports one connection, though.  So running the OpenTherm Monitor is the only way to attach multiple clients to the Gateway.

**Comment by antonlamers** [comment]
Thanks I did it leave empty because I do not use the monitor
Nice holidays
Fijne feestdagen
