### ISSUE TITLE
Support OTGW firmware v5.1.

### ISSUE THREAD

**Issue by PvdGulik** [ebaauw/homebridge-otgw#8]
Hello, I’m using this OTGW-firmware ESP solution:
https://github.com/rvdbreemen/OTGW-firmware

But I can’t get Homebridge-otgw connect to it. I don’t know what I’m doing wrong, or which settings I should use.

Thank you

**Comment by ebaauw** [comment]
Can you connect to this firmware from the OpenTherm Monitor?

**Comment by PvdGulik** [comment]
Yes, thats possible

**Comment by ebaauw** [comment]
Then connect Homebridge OTGW to the web server provided by the OpenTherm Monitor.

**Comment by PvdGulik** [comment]
Which means i have to run contineusly OT Monitor on a PC or Raspberry, which connect directly to the OTGW.
It would be nice if it could connect direct without OT Monitor.

**Comment by ebaauw** [comment]
You can, see the README.  Use the `otgw` setting and enter the hostname and port that OTM uses to connect to the serial server on the NodeMCU on the gateway.  Note that the NodeMCU only supports one concurrent connection.

**Comment by PvdGulik** [comment]
Thanks, one step further, but errors:

[date, time] [OTGW] warning: heartbeat 129, drift 278
[date, time] [OTGW] warning: heartbeat 131, drift 1151
[date, time] [OTGW] warning: heartbeat 132, drift 1032
[date, time] [OTGW] warning: heartbeat 134, drift 573
[date, time] [OTGW] warning: heartbeat 135, drift 267
[date, time] [OTGW] warning: heartbeat 330, drift 1018

What to do?

**Comment by ebaauw** [comment]
These are warnings, not errors.  They are raised because the heart rate isn't triggered at the scheduled time.  If this only happens occasionally, there's probably nothing to worry about.  If this happens structurally, it could indicate an issue with some plugin blocking the NodeJS process (probably by doing synchronous I/O), or you system load being too high.

**Comment by PvdGulik** [comment]
Thanks again for your quick answer.
But still I don't see any accessoires from OTGW.

In the log I see the following:
![image](https://user-images.githubusercontent.com/9421474/110541487-1a9b6a80-8128-11eb-87aa-876e3c27345e.jpeg)

And:![image](https://user-images.githubusercontent.com/9421474/110541516-2555ff80-8128-11eb-8861-05319778a66d.jpeg)

Is this because I use the latest OTGW firmware, version 5.1?

Thanks again!

**Comment by ebaauw** [comment]
Homebridge OTGW issues a PS=0 to the the gateway on startup, to receive a summary message and initialise all characteristics.  It looks like it doesn't like it doesn't understand the response.  Don't know if that's due to the firmware or due to bad communication.  Error 03 is an error returned by the gateway.

**Comment by PvdGulik** [comment]
Helle ebaauw, just checking, does your plug-in only work with Opentherm Gateway version 4.2.6 or 4.3?
Is there any change it will work with 5.1? 

This because I still have issues, don't know how to solve...

Thanks!

**Comment by ebaauw** [comment]
Sorry, I hadn't realised there was new firmware published on http://otgw.tclcode.com/download.html#hexfiles.

Current version was built and tested against 4.2.6.  I don't have the bandwidth nor the resources to test other versions.  I want to support the latest released version, but still I need to install and test 5.1.  I won't be supporting custom firmware.

**Comment by PvdGulik** [comment]
No problem, just let me know when to test, I like to help.

**Comment by ebaauw** [comment]
From the notes:
> The PS=1 output has changed in version 5.0. If using this function, the program processing the information will have to be adapted accordingly. *** POTENTIAL INCOMPATIBILITY ***
Users who need the old format (particularly Domoticz users) should stick to version 4.3.

**Comment by ebaauw** [comment]
Could you try beta v1.3.0-0?

**Comment by PvdGulik** [comment]
/usr/local/lib/node_modules/homebridge-otgw/lib/OtgwMessageParser.js is the file to change ?

**Comment by ebaauw** [comment]
Just install the beta through the Homebridge UI's _Install Previous Version_ feature, or by issuing
```
sudo npm -g i homebridge-otgw@beta
```
from the command line.

**Comment by PvdGulik** [comment]
Thanks, that did the trick. Now its working!![image](https://user-images.githubusercontent.com/9421474/113487066-30494900-94b6-11eb-9f4f-8efded2135c8.png)

**Comment by ebaauw** [comment]
Published v1.3.0.
